<a href="https://colab.research.google.com/github/Shobhit043/pytorch_tutorial/blob/main/Tensor_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [33]:
my_tensor = torch.arange(10)
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Reshape

In [34]:
my_tensor_reshape = my_tensor.reshape(2,5)
print(my_tensor_reshape)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


In [35]:
# Reshape can work with non-contiguous arrays
data = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8]])
reshaped_data = torch.reshape(data, (4, 2))
print(reshaped_data)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])


# View

In [36]:
my_tensor_view = my_tensor.view(2,5)
print(my_tensor_reshape)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


In [37]:
# View only works with contiguous arrays
x = torch.randn(2, 4, 8)
z = x[:, ::2]
try:
    z.view(-1)
except RuntimeError as e:
    print(e)

view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.


### Both view and reshape will get updated if original tensor is updated


In [38]:
my_tensor[0] = 1317
my_tensor

tensor([1317,    1,    2,    3,    4,    5,    6,    7,    8,    9])

In [39]:
print(my_tensor_reshape)

tensor([[1317,    1,    2,    3,    4],
        [   5,    6,    7,    8,    9]])


In [40]:
print(my_tensor_view)

tensor([[1317,    1,    2,    3,    4],
        [   5,    6,    7,    8,    9]])


### To aviod this behaviour we can use .clone()

In [41]:
my_tensor_reshape_copy = my_tensor.reshape(2,5).clone()

# again updating first value
my_tensor[0] = 124

# value still remain same in this tensor
print(my_tensor_reshape_copy)

tensor([[1317,    1,    2,    3,    4],
        [   5,    6,    7,    8,    9]])


In [12]:
# for more info
# https://www.geeksforgeeks.org/whats-the-difference-between-reshape-and-view-in-pytorch/

# Slicing

In [43]:
my_tensor = torch.arange(15.)
my_tensor

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14.])

In [46]:
my_torch_reshape = my_tensor.reshape(3,5)
my_torch_reshape

tensor([[ 0.,  1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14.]])

In [49]:
my_torch_reshape[1:2,1:3]

tensor([[6., 7.]])