<a href="https://colab.research.google.com/github/Shobhit043/pytorch_tutorial/blob/main/Tensor_math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch

In [4]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

# Addition

In [5]:
tensor_a+tensor_b

tensor([ 6,  8, 10, 12])

In [6]:
torch.add(tensor_a,tensor_b)

tensor([ 6,  8, 10, 12])

In [7]:
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

# Subtraction

In [8]:
tensor_a-tensor_b

tensor([-4, -4, -4, -4])

In [9]:
torch.sub(tensor_a,tensor_b)

tensor([-4, -4, -4, -4])

In [10]:
tensor_a.sub(tensor_b)

tensor([-4, -4, -4, -4])

# Multiplication

In [11]:
tensor_a*tensor_b

tensor([ 5, 12, 21, 32])

In [12]:
torch.mul(tensor_a,tensor_b)

tensor([ 5, 12, 21, 32])

In [13]:
tensor_a.mul(tensor_b)

tensor([ 5, 12, 21, 32])

# Division

In [14]:
tensor_a/tensor_b

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [15]:
torch.div(tensor_a,tensor_b)

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [16]:
tensor_a.div(tensor_b)

tensor([0.2000, 0.3333, 0.4286, 0.5000])

# Power

In [17]:
tensor_a**tensor_b

tensor([    1,    64,  2187, 65536])

In [18]:
torch.pow(tensor_a,tensor_b)

tensor([    1,    64,  2187, 65536])

In [19]:
tensor_a.pow(tensor_b)

tensor([    1,    64,  2187, 65536])

# Modulus

In [20]:
tensor_a%tensor_b

tensor([1, 2, 3, 4])

In [21]:
torch.remainder(tensor_a,tensor_b)

tensor([1, 2, 3, 4])

In [22]:
tensor_a.remainder(tensor_b)

tensor([1, 2, 3, 4])

# Reassingment

In [ ]:
tensor_a.add_(tensor_b) # reassings the output to tensor a

tensor([ 6,  8, 10, 12])

In [23]:
tensor_a.sub_(tensor_b) # reassings the output to tensor a

tensor([-4, -4, -4, -4])

In [24]:
tensor_a.mul_(tensor_b) # reassings the output to tensor a

tensor([-20, -24, -28, -32])

In [26]:
# tensor_a.div_(tensor_b) # could give error if type of tensor_a is not float

In [27]:
tensor_a.remainder_(tensor_b)

tensor([0, 0, 0, 0])