<a href="https://colab.research.google.com/github/Shobhit043/pytorch_tutorial/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [3]:
# List
my_list_1d = [1,2,3,4]
my_list_2d = [[1,2,3,4],[5,6,7,8]]

print(my_list_1d)
print(my_list_2d)

[1, 2, 3, 4]
[[1, 2, 3, 4], [5, 6, 7, 8]]


In [5]:
# numpy arrays
my_array_1d = np.random.rand(4)
my_array_2d = np.random.rand(2,4)

print(my_array_1d)
print(my_array_2d)

[0.8971661  0.71368719 0.96343376 0.63824134]
[[0.11458085 0.60059894 0.81499856 0.29849728]
 [0.14108323 0.93972538 0.31896777 0.01566467]]


In [6]:
my_array_1d.dtype

dtype('float64')

defualt type of numpy arrays is float64

In [17]:
# Tensors
my_tensor_1d = torch.randn(4)
my_tensor_2d = torch.randn(3,4)

print(my_tensor_1d)
print(my_tensor_2d)

tensor([0.1824, 0.5718, 0.7956, 0.3517])
tensor([[ 0.9507,  1.9796, -0.5829, -0.3277],
        [-0.1093,  0.1304, -1.2399, -0.1324],
        [-1.4981, -1.0393, -0.0373, -0.8842]])


In [18]:
my_tensor_1d.dtype

torch.float32

default type of tensor is float32

In [19]:
my_tensor_from_array = torch.tensor(my_array_1d)
print(my_tensor_from_array)

tensor([0.8972, 0.7137, 0.9634, 0.6382], dtype=torch.float64)


converting array to tensor

In [20]:
print(my_tensor_2d[2,2])

tensor(-0.0373)


Using python slicing to access elements of the tensor just like normal arrays

In [22]:
x = torch.tensor([[1]])
x.item()

1

Use torch.Tensor.item() to get a Python number from a tensor containing a single value: