In [14]:
!pip install torchinfo

In [15]:
import torch
print(torch.__version__)

import torch.nn as nn
from torchinfo import summary

2.6.0+cu124


## Perceptron

In [16]:
class Perceptron(nn.Module):
  def __init__(self, num_features):
    super().__init__() # calling __init__ function from nn.Module

    self.Linear = nn.Linear(num_features,1,dtype=torch.float32)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):
    y = self.Linear(features)
    y_pred = self.sigmoid(y)

    return y_pred

In [22]:
X = torch.rand(10,3,dtype = torch.float32)

In [23]:
model = Perceptron(X.shape[1])

In [24]:
model.Linear.weight

Parameter containing:
tensor([[ 0.1953, -0.2740, -0.2207]], requires_grad=True)

In [25]:
model.Linear.bias

Parameter containing:
tensor([0.3299], requires_grad=True)

In [26]:
model(X)

tensor([[0.4787],
        [0.5349],
        [0.5202],
        [0.5628],
        [0.5484],
        [0.5619],
        [0.5783],
        [0.5884],
        [0.5822],
        [0.5142]], grad_fn=<SigmoidBackward0>)

In [27]:
summary(model, (10,3))

Layer (type:depth-idx)                   Output Shape              Param #
Perceptron                               [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   4
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 4
Trainable params: 4
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

## MLP

In [28]:
class MLP(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features, 3),
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid()
    )

  def forward(self,features):
    y_pred = self.network(features)
    return y_pred

In [30]:
model = MLP(X.shape[1])

In [37]:
model(X)

tensor([[0.6481],
        [0.6579],
        [0.6620],
        [0.6455],
        [0.6338],
        [0.6734],
        [0.6701],
        [0.6389],
        [0.6303],
        [0.6613]], grad_fn=<SigmoidBackward0>)

In [38]:
summary(model,(10,3))

Layer (type:depth-idx)                   Output Shape              Param #
MLP                                      [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   12
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 16
Trainable params: 16
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [43]:
model.network[0].weight

Parameter containing:
tensor([[ 0.5241,  0.0613,  0.5401],
        [ 0.2645,  0.1150, -0.3196],
        [-0.0356, -0.5374,  0.2671]], requires_grad=True)

In [44]:
model.network[0].bias

Parameter containing:
tensor([0.0098, 0.5471, 0.4087], requires_grad=True)